### ISSUE TITLE
Form appearance

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/cccheck#16]
### This is the current appearance of the form.
![cccheck_form_actual](https://user-images.githubusercontent.com/1015013/66901760-b1b4cf00-efd5-11e9-86f6-2bff64a719a7.png)

### This is the expected final appearance of the form.
![cccheck_form_default](https://user-images.githubusercontent.com/1015013/66901317-d8bed100-efd4-11e9-983a-bfcb09fc810b.png)
[Figma mockup link](https://www.figma.com/file/ZtNau09ryWbmPwl388WOvs/cccheck-form?node-id=19%3A22)

**Comment by RuanAragao** [comment]
Look @joshuiaclan

**Comment by joshuiaclan** [comment]
Allright will send a PR later :) Thank you again!

**Comment by joshuiaclan** [comment]
Would you like me to use font awesome for the logo? It seems similar.
![image](https://user-images.githubusercontent.com/42407891/66910204-b498d980-f040-11e9-9e03-f44f9f7ee93b.png)

**Comment by joshuiaclan** [comment]
Would you like me to use font awesome? The logo looks similar :)
![image](https://user-images.githubusercontent.com/42407891/66910293-dd20d380-f040-11e9-8f4e-2bbd6c4eb15a.png)

**Comment by joshuiaclan** [comment]
Hi this is check out what I did before I ask for a pull request

**Comment by joshuiaclan** [comment]
Hi @RuanAragao. Here is a sample of what I made and my pull request - [PR17](https://github.com/RuanAragao/cccheck/pull/17)

![image](https://user-images.githubusercontent.com/42407891/66919338-bae48100-f053-11e9-8943-4c59eab952fd.png)

![image](https://user-images.githubusercontent.com/42407891/66919534-0f87fc00-f054-11e9-8d21-94f166c2ffc0.png)

**Comment by RuanAragao** [comment]
Great job!
