### ISSUE TITLE
Make the exemple page responsive

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/cccheck#18]
## Mockup for reference
![cccheck_form_mobile](https://user-images.githubusercontent.com/1015013/66941751-f95f4900-f01d-11e9-9561-0e92c2db136b.png)
[Figma mockup](https://www.figma.com/file/ZtNau09ryWbmPwl388WOvs/cccheck-form?node-id=24%3A0)

**Comment by sigfriedCub1990** [comment]
I'll take this :) @RuanAragao
