### ISSUE TITLE
Build a better example page

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/cccheck#5]
improve the page __index.html__

**Comment by gupta-ji6** [comment]
I would like to work on this.  I will send a PR by tonight.

**Comment by iishyfishyy** [comment]
Created [PR](https://github.com/RuanAragao/cccheck/pull/7).

**Comment by RuanAragao** [comment]
Hello, this is the mockup for reference to form style. 
![cccheck_1](https://user-images.githubusercontent.com/1015013/66757654-f8d67f00-ee72-11e9-9db3-55d5c9546ece.png)

In this issue, non add the mask, we have a issue for this #1. 
![cccheck_2](https://user-images.githubusercontent.com/1015013/66757657-fc6a0600-ee72-11e9-8d49-0618a0aa9efe.png)

The use of a css library is not so appreciated because it is too small and simple a project. But not totally declined, depending on the codical and visual result.

**Comment by RuanAragao** [comment]
Migrate for the #8
