### ISSUE TITLE
Form problems

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/cccheck#8]
- Not show icons. 
- Inputs size small.

![image](https://user-images.githubusercontent.com/1015013/66760284-283bba80-ee78-11e9-9818-510b976da1a0.png)

Make form follow mockup in the https://github.com/RuanAragao/cccheck/issues/5#issuecomment-541709952
### This is the final aspect of the form with the data entered.
![cccheck form](https://user-images.githubusercontent.com/1015013/66761093-b5cbda00-ee79-11e9-8ba4-43e131693a69.png)
The brand icon changes according to the card you inserted. Check out the sprites in css.

**Comment by joshuiaclan** [comment]
Hi! Can I take this?

**Comment by RuanAragao** [comment]
Sure @joshuiaclan

**Comment by joshuiaclan** [comment]
Alright! Thanks a lot!

**Comment by RuanAragao** [comment]
Figma mockup:
https://www.figma.com/file/ZtNau09ryWbmPwl388WOvs/cccheck-form?node-id=0%3A1

**Comment by guilhermeorcezi** [comment]
taken?

**Comment by joshuiaclan** [comment]
Created a pull request please check

**Comment by joshuiaclan** [comment]
Sure no problem, Just to make things clear, I have to create 2 samples?

**Comment by RuanAragao** [comment]
I found the main problem, css was inserted straight into index.html instead of being preprocessed.

**Comment by joshuiaclan** [comment]
Created another pull request please check again.

**Comment by RuanAragao** [comment]
Issue of the form desing --> #16
